field: a1ec3624-bc4f-47d1-857a-94c9ff8a8e7f # Content
fieldLayouts:
  e67b9bd2-369c-4943-add5-6e234ad78aae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 83b1238e-e61c-4182-a7c7-d685d7110d25 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfee0161-0cd8-4818-b0b3-482505019f91
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8906d457-7b9c-4470-815f-6340084519c6 # Media position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 008febf5-5248-4513-8c61-2c3c07c79e72
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: c71ba68f-4d87-4fd4-8b3c-918f136caae1 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a17a339-2f5f-4bd4-9bd8-9fba0f52a6e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c82df61-10c2-44da-821a-bc9a07acdb6a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d7db30-e633-4e92-88a0-cbb14a8f27fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63a3bac7-3a9f-408c-8cd6-967febd07e83 # Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83e8ae42-4c48-45f3-9491-0117e73e72d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4758ca68-161b-41b7-a10f-c52568a27b8a # Text size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf693962-37de-4f07-a088-bcb0d664220a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8729bbc4-30be-4411-9dfb-6636e1a4e38b # Text position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9f349d8-03b4-482f-9b9e-d2c1d0a3a67a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 03b2486a-ac98-4cd8-b645-a61ad55f5f9b # Space above
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1b9ea14-31a2-4747-b8c4-924658ffd0d1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 33d50610-b911-4a82-913b-88cfd9b65951 # Space below
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea30cb24-ec51-49eb-bbba-de8749c0b643
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 54ed6ecd-0292-498b-ba72-f43607e5bfee
        userCondition: null
fields:
  0c82df61-10c2-44da-821a-bc9a07acdb6a: # Text
    columnSuffix: jxpzrrzr
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  03b2486a-ac98-4cd8-b645-a61ad55f5f9b: # Space above
    columnSuffix: xuodksiz
    contentColumnType: string
    fieldGroup: null
    handle: spaceAbove
    instructions: null
    name: 'Space above'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - '-lg'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - '-0'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  33d50610-b911-4a82-913b-88cfd9b65951: # Space below
    columnSuffix: pchgrtlw
    contentColumnType: string
    fieldGroup: null
    handle: spaceBelow
    instructions: null
    name: 'Space below'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - '-lg'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - '-0'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  63a3bac7-3a9f-408c-8cd6-967febd07e83: # Table
    columnSuffix: gvmrhpby
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: null
    name: Table
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Column 1'
                -
                  - handle
                  - column1
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Column 2'
                -
                  - handle
                  - column2
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  83b1238e-e61c-4182-a7c7-d685d7110d25: # Media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: null
    name: Media
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:e342c5ac-0f5e-4aaa-b4b4-17dc7dab6a10' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e342c5ac-0f5e-4aaa-b4b4-17dc7dab6a10' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4758ca68-161b-41b7-a10f-c52568a27b8a: # Text size
    columnSuffix: aemeosta
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: null
    name: 'Text size'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - lg
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - md
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  8729bbc4-30be-4411-9dfb-6636e1a4e38b: # Text position
    columnSuffix: vzdaqdxi
    contentColumnType: string
    fieldGroup: null
    handle: textPosition
    instructions: null
    name: 'Text position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - between
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - end
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  8906d457-7b9c-4470-815f-6340084519c6: # Media position
    columnSuffix: nytoojpl
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: null
    name: 'Media position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  c71ba68f-4d87-4fd4-8b3c-918f136caae1: # Heading
    columnSuffix: gdevmfxk
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textWithMedia
name: 'Text with media'
sortOrder: 4
