columnSuffix: null
contentColumnType: string
fieldGroup: 12cc6622-ac89-4a7b-a6d8-10d1f01b9c38 # Common
handle: contentMatrix
instructions: null
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentmatrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
